 spring:
    data:
        mongodb:
            host: ds163745.mlab.com
            port: 63745
            database: users
            username: arsw
            password: arsw1 
 spring:
    redis:
       host: 54.245.48.146
       port: 6378



